services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      MONGO_CONNECTION_STRING: 'mongodb://mongo:27017'
      REPORTS_CRON: '* * * 1 * * '
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017